version: '3'

services:
  mongo_db:
    image: "bitnami/mongodb:latest"
    ports:
      - "27018:27017"
    volumes:
      - 'mongodb_data:/bitnami'
  api:
    restart: on-failure
    build: .
    env_file:
      - .env
    depends_on:
      - mongo_db
    ports:
      - "2040:2040"

volumes:
  mongodb_data:
    driver: local