version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mongo_db:
    container_name: mongo-db
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    networks:
      - app-tier
    volumes:
      - 'mongodb_data:/bitnami'
  api:
    container_name: moonpay-api
    image: moonpay-api
    networks:
      - app-tier
    env_file:
      - .env
    depends_on:
      - mongo_db
    ports:
      - "8080:8080/tcp"
    environment:
      - DATA_MONGODB_HOST=mongo_db
    links:
      - mongo_db

volumes:
  mongodb_data:
    driver: local